[build]
  publish = "lumiere-cosmetics"
  functions = "netlify/functions"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://admirable-ganache-f75333.netlify.app"
